import type { Fact, LonLat } from './types';
import type { WalkingRoute } from './providers';

export interface SampleRouteData {
  id: string;
  title: string;
  isSample: boolean;
  start: { name: string; position: LonLat };
  end: { name: string; position: LonLat };
  walkingRoute: WalkingRoute;
  facts: Fact[];
}

export interface SamplePlaceData {
  id: string;
  name: string;
  label: string;
  position: LonLat;
  isSample: boolean;
  category?: string;
  facts: Fact[];
}

export interface DemoSnapshot {
  snapshotVersion: string;
  isSample: boolean;
  label: string;
  generatedAt: string;
  demoArea: string;
  sources: Array<{ name: string; url: string; licence: string }>;
  routes: SampleRouteData[];
  places: SamplePlaceData[];
}

export const DEMO_SNAPSHOT: DemoSnapshot = {
  snapshotVersion: '1.0.0',
  isSample: true,
  label: 'DANE PRZYKŁADOWE (Offline Demo Snapshot Kraków)',
  generatedAt: '2026-10-03T11:00:00.000Z',
  demoArea: 'Rynek Główny – Kazimierz – Wawel – Planty',
  sources: [
    {
      name: 'OpenStreetMap',
      url: 'https://www.openstreetmap.org',
      licence: 'ODbL',
    },
    {
      name: 'Mapy.com',
      url: 'https://developer.mapy.com',
      licence: 'Mapy.com API Terms',
    },
  ],
  routes: [
    {
      id: 'sample-route-rynek-wawel',
      title: 'Rynek Główny → Wawel (ul. Grodzka)',
      isSample: true,
      start: { name: 'Rynek Główny', position: { lon: 19.9373, lat: 50.0619 } },
      end: { name: 'Zamek Królewski na Wawelu', position: { lon: 19.9354, lat: 50.0544 } },
      walkingRoute: {
        provider: 'Mapy.com (DANE PRZYKŁADOWE)',
        lengthMetres: 920,
        durationSeconds: 750,
        retrievedAt: '2026-10-03T11:00:00Z',
        coordinates: [
          [19.9373, 50.0619],
          [19.9374, 50.061],
          [19.9377, 50.0598],
          [19.938, 50.0583],
          [19.9383, 50.0569],
          [19.937, 50.0556],
          [19.9354, 50.0544],
        ],
      },
      facts: [
        {
          id: 'fact-sett-rynek',
          subject: { type: 'segment', ref: 'way/rynek-glowny', lat: 50.0618, lon: 19.9373 },
          criterion: 'surface',
          value: 'cobblestone',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/way/rynek-glowny',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2025-05-12T14:20:00Z',
        },
        {
          id: 'fact-crossing-dominikanska',
          subject: {
            type: 'crossing',
            ref: 'node/cross-dominikanska',
            lat: 50.0598,
            lon: 19.9377,
          },
          criterion: 'crossing',
          value: 'traffic_signals=yes, tactile_paving=yes',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/cross-dominikanska',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-10T09:00:00Z',
        },
        {
          id: 'fact-kerb-dominikanska',
          subject: {
            type: 'crossing',
            ref: 'node/kerb-dominikanska',
            lat: 50.0598,
            lon: 19.9377,
          },
          criterion: 'kerb',
          value: '50 mm',
          unit: 'mm',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/kerb-dominikanska',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-10T09:00:00Z',
        },
        {
          id: 'fact-steps-kosciol-piotra',
          subject: { type: 'segment', ref: 'way/steps-piotr', lat: 50.0569, lon: 19.9383 },
          criterion: 'steps',
          value: '6 stopni, ramp=no',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/way/steps-piotr',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2024-08-20T10:15:00Z',
        },
        {
          id: 'fact-kerb-senatorska-high',
          subject: {
            type: 'crossing',
            ref: 'node/kerb-senatorska',
            lat: 50.0556,
            lon: 19.937,
          },
          criterion: 'kerb',
          value: '140 mm',
          unit: 'mm',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/kerb-senatorska',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2023-11-04T12:00:00Z',
        },
        {
          id: 'fact-crossing-wawel-unknown',
          subject: {
            type: 'crossing',
            ref: 'node/cross-podzamcze',
            lat: 50.0545,
            lon: 19.9355,
          },
          criterion: 'kerb',
          value: 'brak pomiaru',
          status: 'unknown',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/cross-podzamcze',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
        },
      ],
    },
    {
      id: 'sample-route-rynek-wawel-accessible',
      title: 'Rynek Główny → Wawel (Bez barier, przez Planty)',
      isSample: true,
      start: { name: 'Rynek Główny', position: { lon: 19.9373, lat: 50.0619 } },
      end: { name: 'Zamek Królewski na Wawelu', position: { lon: 19.9354, lat: 50.0544 } },
      walkingRoute: {
        provider: 'GraphHopper Accessible (DANE PRZYKŁADOWE)',
        lengthMetres: 1080,
        durationSeconds: 880,
        retrievedAt: '2026-10-03T11:00:00Z',
        coordinates: [
          [19.9373, 50.0619],
          [19.9358, 50.0618],
          [19.9348, 50.0605],
          [19.9342, 50.0588],
          [19.934, 50.057],
          [19.9344, 50.0552],
          [19.9354, 50.0544],
        ],
      },
      facts: [
        {
          id: 'fact-surface-planty-asphalt',
          subject: { type: 'segment', ref: 'way/planty-asphalt', lat: 50.0605, lon: 19.9348 },
          criterion: 'surface',
          value: 'asphalt',
          status: 'verified',
          source: {
            name: 'OpenStreetMap / ZZM Kraków',
            url: 'https://osm.org/way/planty-asphalt',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-12T10:00:00Z',
        },
        {
          id: 'fact-kerb-planty-low',
          subject: { type: 'crossing', ref: 'node/kerb-planty-low', lat: 50.0588, lon: 19.9342 },
          criterion: 'kerb',
          value: '10 mm',
          unit: 'mm',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/kerb-planty-low',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-12T10:00:00Z',
        },
        {
          id: 'fact-ramp-planty-gentle',
          subject: { type: 'segment', ref: 'way/ramp-planty', lat: 50.057, lon: 19.934 },
          criterion: 'ramp',
          value: 'rampa o nachyleniu 4% z obustronnymi poręczami',
          status: 'verified',
          source: {
            name: 'Miejski System Informacji Przestrzennej (MSIP)',
            url: 'https://msip.krakow.pl',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-12T10:00:00Z',
        },
        {
          id: 'fact-crossing-franciszkanska-tactile',
          subject: { type: 'crossing', ref: 'node/cross-franciszkanska', lat: 50.0588, lon: 19.9342 },
          criterion: 'crossing',
          value: 'sygnalizacja dźwiękowa, pasy dotykowe',
          status: 'verified',
          source: {
            name: 'ZTP Kraków (Open Data)',
            url: 'https://ztp.krakow.pl',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-12T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-route-kazimierz-planty',
      title: 'Kazimierz (Plac Nowy) → Planty',
      isSample: true,
      start: { name: 'Plac Nowy', position: { lon: 19.9449, lat: 50.0519 } },
      end: { name: 'Planty (Poczta Główna)', position: { lon: 19.9423, lat: 50.0592 } },
      walkingRoute: {
        provider: 'Mapy.com (DANE PRZYKŁADOWE)',
        lengthMetres: 870,
        durationSeconds: 700,
        retrievedAt: '2026-10-03T11:00:00Z',
        coordinates: [
          [19.9449, 50.0519],
          [19.9458, 50.0531],
          [19.9448, 50.0555],
          [19.9436, 50.0573],
          [19.9423, 50.0592],
        ],
      },
      facts: [
        {
          id: 'fact-surface-plac-nowy',
          subject: { type: 'segment', ref: 'way/plac-nowy', lat: 50.052, lon: 19.945 },
          criterion: 'surface',
          value: 'paving_stones',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/way/plac-nowy',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
        },
        {
          id: 'fact-kerb-miodowa',
          subject: {
            type: 'crossing',
            ref: 'node/kerb-miodowa',
            lat: 50.0532,
            lon: 19.9457,
          },
          criterion: 'kerb',
          value: '20 mm',
          unit: 'mm',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/kerb-miodowa',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
        },
        {
          id: 'fact-tram-starowislna',
          subject: {
            type: 'crossing',
            ref: 'way/tram-starowislna',
            lat: 50.0555,
            lon: 19.9448,
          },
          criterion: 'crossing',
          value: 'torowisko tramwajowe, sygnalizacja',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/way/tram-starowislna',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
        },
      ],
    },
  ],
  places: [
    {
      id: 'sample-place-sukiennice',
      name: 'Sukiennice (Galeria Sztuki)',
      label: 'Rynek Główny 1/3, Kraków',
      position: { lon: 19.9373, lat: 50.0619 },
      isSample: true,
      facts: [
        {
          id: 'place-sukiennice-entrance',
          subject: {
            type: 'entrance',
            ref: 'node/sukiennice-entrance',
            lat: 50.0619,
            lon: 19.9373,
          },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście płaskie od strony Wieży Ratuszowej, drzwi automatyczne szer. 110 cm)',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/sukiennice-entrance',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-03-15T12:00:00Z',
        },
        {
          id: 'place-sukiennice-elevator',
          subject: {
            type: 'place',
            ref: 'node/sukiennice-lift',
            lat: 50.0619,
            lon: 19.9373,
          },
          criterion: 'highway:elevator',
          value: 'winda osobowa dostępna na piętro (I piętro Galeria Malarstwa)',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/sukiennice-lift',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-03-15T12:00:00Z',
        },
        {
          id: 'place-sukiennice-toilet',
          subject: {
            type: 'place',
            ref: 'node/sukiennice-wc',
            lat: 50.0619,
            lon: 19.9373,
          },
          criterion: 'toilets:wheelchair',
          value: 'yes (toaleta przystosowana, poręcze, przestrzeń manewrowa 160x160 cm)',
          status: 'verified',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/sukiennice-wc',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-03-15T12:00:00Z',
        },
        {
          id: 'place-sukiennice-surroundings',
          subject: {
            type: 'place',
            ref: 'way/sukiennice-podcienia',
            lat: 50.0619,
            lon: 19.9373,
          },
          criterion: 'surface:surroundings',
          value: 'płyty kamienne równe, podcienia bezprogowe',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/way/sukiennice-podcienia',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-conflict-demo',
      name: 'Kamienica Grodzka (Symulacja R7: Dane Sprzeczne)',
      label: 'ul. Grodzka 12, Kraków',
      position: { lon: 19.9378, lat: 50.0585 },
      isSample: true,
      facts: [
        {
          id: 'fact-conflict-1',
          subject: {
            type: 'place',
            ref: 'building/grodzka-12',
            lat: 50.0585,
            lon: 19.9378,
          },
          criterion: 'wheelchair',
          value: 'yes (oznaczono budynek jako dostępny)',
          status: 'community',
          source: {
            name: 'OpenStreetMap (tag budynku)',
            url: 'https://osm.org/way/12345',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2023-01-10T12:00:00Z',
        },
        {
          id: 'fact-conflict-2',
          subject: {
            type: 'entrance',
            ref: 'building/grodzka-12',
            lat: 50.0585,
            lon: 19.9378,
          },
          criterion: 'wheelchair',
          value: 'no (węzeł wejścia: 5 stromych stopni bez podjazdu)',
          status: 'community',
          source: {
            name: 'OpenStreetMap (węzeł drzwi)',
            url: 'https://osm.org/node/67890',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2024-05-15T08:30:00Z',
        },
      ],
    },
    {
      id: 'sample-place-krzysztofory',
      name: 'Pałac Krzysztofory (Muzeum Krakowa - KSDK)',
      label: 'Rynek Główny 35, Kraków',
      position: { lon: 19.9366, lat: 50.0622 },
      isSample: true,
      facts: [
        {
          id: 'place-krzysztofory-entrance',
          subject: { type: 'entrance', ref: 'node/krzysztofory-entrance', lat: 50.0622, lon: 19.9366 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście bezbarierowe, linie naprowadzające, pętla indukcyjna w kasie)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-krzysztofory-elevator',
          subject: { type: 'place', ref: 'node/krzysztofory-elevators', lat: 50.0622, lon: 19.9366 },
          criterion: 'highway:elevator',
          value: '3 windy osobowe (wymiary 1.05 x 2.05 m), zapowiedzi głosowe, alfabet Braille',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-krzysztofory-toilets',
          subject: { type: 'place', ref: 'node/krzysztofory-wc', lat: 50.0622, lon: 19.9366 },
          criterion: 'toilets:wheelchair',
          value: 'yes (toalety przystosowane dla wózków, przewijak dla dzieci)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-krzysztofory-ramp',
          subject: { type: 'place', ref: 'node/krzysztofory-platform', lat: 50.0622, lon: 19.9366 },
          criterion: 'ramp',
          value: 'platforma przyschodowa na poziom -1 (udźwig maks. 160 kg)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-wieza-ratuszowa',
      name: 'Wieża Ratuszowa (Muzeum Krakowa - KSDK)',
      label: 'Rynek Główny 1, Kraków',
      position: { lon: 19.9368, lat: 50.0615 },
      isSample: true,
      facts: [
        {
          id: 'place-wieza-entrance',
          subject: { type: 'entrance', ref: 'node/wieza-entrance', lat: 50.0615, lon: 19.9368 },
          criterion: 'entrance:wheelchair',
          value: 'no (obiekt zabytkowy niedostępny dla osób poruszających się na wózkach)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-wieza-steps',
          subject: { type: 'place', ref: 'node/wieza-stairs', lat: 50.0615, lon: 19.9368 },
          criterion: 'steps',
          value: '110 wąskich i stromych stopni kamiennych o nieregularnej wysokości, brak windy',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-wieza-toilets',
          subject: { type: 'place', ref: 'node/wieza-wc', lat: 50.0615, lon: 19.9368 },
          criterion: 'toilets:wheelchair',
          value: 'no (brak toalet w obiekcie)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-barbakan',
      name: 'Barbakan (Muzeum Krakowa - KSDK)',
      label: 'ul. Basztowa / Planty, Kraków',
      position: { lon: 19.9417, lat: 50.0655 },
      isSample: true,
      facts: [
        {
          id: 'place-barbakan-entrance',
          subject: { type: 'entrance', ref: 'node/barbakan-entrance', lat: 50.0655, lon: 19.9417 },
          criterion: 'entrance:wheelchair',
          value: 'limited (wejście przez drewniany mostek z pochylnią)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-barbakan-surface',
          subject: { type: 'place', ref: 'node/barbakan-courtyard', lat: 50.0655, lon: 19.9417 },
          criterion: 'surface',
          value: 'cobblestone (zabytkowy, nieregularny bruk na dziedzińcu)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-barbakan-steps',
          subject: { type: 'place', ref: 'node/barbakan-stairs', lat: 50.0655, lon: 19.9417 },
          criterion: 'steps',
          value: 'schody na górne kondygnacje bez poręczy, brak windy',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-stara-synagoga',
      name: 'Stara Synagoga (Muzeum Krakowa - KSDK)',
      label: 'ul. Szeroka 24, Kraków (Kazimierz)',
      position: { lon: 19.9485, lat: 50.0506 },
      isSample: true,
      facts: [
        {
          id: 'place-synagoga-entrance',
          subject: { type: 'entrance', ref: 'node/synagoga-entrance', lat: 50.0506, lon: 19.9485 },
          criterion: 'entrance:wheelchair',
          value: 'no (brak bezpośredniego wejścia bezbarierowego, schody)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-synagoga-steps',
          subject: { type: 'place', ref: 'node/synagoga-stairs', lat: 50.0506, lon: 19.9485 },
          criterion: 'steps',
          value: 'schody prowadzące na plac wejściowy i do Sali Męskiej, brak windy',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-muzeum-podgorza',
      name: 'Muzeum Podgórza (Muzeum Krakowa - KSDK)',
      label: 'ul. Powstańców Wielkopolskich / Limanowskiego 51, Kraków',
      position: { lon: 19.9547, lat: 50.0441 },
      isSample: true,
      facts: [
        {
          id: 'place-podgorze-entrance',
          subject: { type: 'entrance', ref: 'node/podgorze-entrance', lat: 50.0441, lon: 19.9547 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście bezprogowe od strony dziedzińca, kasa z obniżonym blatem i pętlą indukcyjną)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-podgorze-elevator',
          subject: { type: 'place', ref: 'node/podgorze-elevator', lat: 50.0441, lon: 19.9547 },
          criterion: 'highway:elevator',
          value: 'winda osobowa o wymiarach 1.58 x 2.10 m z oznaczeniami w alfabecie Braille',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-podgorze-toilet',
          subject: { type: 'place', ref: 'node/podgorze-wc', lat: 50.0441, lon: 19.9547 },
          criterion: 'toilets:wheelchair',
          value: 'yes (toaleta w pełni dostosowana dla osób z niepełnosprawnościami)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/muzeum_krakowa/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-stale-demo',
      name: 'Restauracja Staromiejska (Symulacja R8: Dane Przedawnione)',
      label: 'ul. Szewska 8, Kraków',
      position: { lon: 19.9355, lat: 50.0628 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'fact-stale-1',
          subject: { type: 'place', ref: 'node/szewska-8', lat: 50.0628, lon: 19.9355 },
          criterion: 'wheelchair',
          value: 'limited',
          status: 'community',
          source: {
            name: 'OpenStreetMap',
            url: 'https://osm.org/node/szewska-8',
            licence: 'ODbL',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastEditedAt: '2021-02-14T10:00:00Z',
          lastConfirmedAt: '2021-02-14T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-mocak',
      name: 'MOCAK Muzeum Sztuki Współczesnej (KSDK)',
      label: 'ul. Lipowa 4, Kraków (Zabłocie)',
      position: { lon: 19.9612, lat: 50.0475 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'place-mocak-entrance',
          subject: { type: 'entrance', ref: 'node/mocak-entrance', lat: 50.0475, lon: 19.9612 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście główne na poziomie chodnika, drzwi automatyczne, kasa z pętlą indukcyjną)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/mocak/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-mocak-elevator',
          subject: { type: 'place', ref: 'node/mocak-elevator', lat: 50.0475, lon: 19.9612 },
          criterion: 'highway:elevator',
          value: 'dwie windy wielkogabarytowe łączące poziomy -1, 0 i 1 z komunikatami głosowymi',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/mocak/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-mocak-toilet',
          subject: { type: 'place', ref: 'node/mocak-toilet', lat: 50.0475, lon: 19.9612 },
          criterion: 'toilets:wheelchair',
          value: 'yes (toaleta przystosowana dla wózków, przycisk przyzywowy SOS)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://bip.krakow.pl/mocak/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-mnk-glowny',
      name: 'MNK Gmach Główny (Muzeum Narodowe)',
      label: 'al. 3 Maja 1, Kraków',
      position: { lon: 19.9248, lat: 50.0598 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'place-mnk-entrance',
          subject: { type: 'entrance', ref: 'node/mnk-entrance', lat: 50.0598, lon: 19.9248 },
          criterion: 'entrance:wheelchair',
          value: 'yes (pochylnia zewnętrzna od strony al. 3 Maja, drzwi z przyciskiem)',
          status: 'verified',
          source: {
            name: 'Deklaracja Dostępności MNK / BIP',
            url: 'https://mnk.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-mnk-elevator',
          subject: { type: 'place', ref: 'node/mnk-elevator', lat: 50.0598, lon: 19.9248 },
          criterion: 'highway:elevator',
          value: 'windy osobowe na wszystkie kondygnacje wystaw stałych i czasowych',
          status: 'verified',
          source: {
            name: 'Deklaracja Dostępności MNK / BIP',
            url: 'https://mnk.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-cricoteka',
      name: 'Cricoteka (Ośrodek Sztuki T. Kantora - KSDK)',
      label: 'ul. Nadwiślańska 2-4, Kraków (Podgórze)',
      position: { lon: 19.9532, lat: 50.0463 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'place-cricoteka-entrance',
          subject: { type: 'entrance', ref: 'node/cricoteka-entrance', lat: 50.0463, lon: 19.9532 },
          criterion: 'entrance:wheelchair',
          value: 'yes (plac wejściowy na poziomie bulwaru wiślanego, wejście bezstopniowe)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://cricoteka.pl/bip/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-cricoteka-elevator',
          subject: { type: 'place', ref: 'node/cricoteka-elevator', lat: 50.0463, lon: 19.9532 },
          criterion: 'highway:elevator',
          value: 'przeszklone windy wieloosobowe łączące plac, sale wystawowe i kawiarnię widokową',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności (KSDK)',
            url: 'https://cricoteka.pl/bip/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-slowacki',
      name: 'Teatr im. Juliusza Słowackiego (KSDK)',
      label: 'pl. Świętego Ducha 1, Kraków',
      position: { lon: 19.9431, lat: 50.0635 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'place-slowacki-entrance',
          subject: { type: 'entrance', ref: 'node/slowacki-entrance', lat: 50.0635, lon: 19.9431 },
          criterion: 'entrance:wheelchair',
          value: 'limited (wejście dla osób z niepełnosprawnością od strony Plant z pochylnią)',
          status: 'verified',
          source: {
            name: 'BIP Teatr im. J. Słowackiego / Deklaracja Dostępności',
            url: 'https://teatrwkrakowie.pl/bip/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-slowacki-lift',
          subject: { type: 'place', ref: 'node/slowacki-lift', lat: 50.0635, lon: 19.9431 },
          criterion: 'highway:elevator',
          value: 'platforma schodowa na poziom widowni parteru, pętla indukcyjna na widowni',
          status: 'verified',
          source: {
            name: 'BIP Teatr im. J. Słowackiego / Deklaracja Dostępności',
            url: 'https://teatrwkrakowie.pl/bip/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-nck',
      name: 'Nowohuckie Centrum Kultury (NCK - KSDK)',
      label: 'al. Jana Pawła II 232, Kraków (Nowa Huta)',
      position: { lon: 20.0368, lat: 50.0712 },
      category: 'culture',
      isSample: true,
      facts: [
        {
          id: 'place-nck-entrance',
          subject: { type: 'entrance', ref: 'node/nck-entrance', lat: 50.0712, lon: 20.0368 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście główne bezprogowe z poziomu placu Centralnego, szerokie drzwi)',
          status: 'verified',
          source: {
            name: 'BIP NCK / Deklaracja Dostępności (KSDK)',
            url: 'https://nck.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-nck-elevator',
          subject: { type: 'place', ref: 'node/nck-elevator', lat: 50.0712, lon: 20.0368 },
          criterion: 'highway:elevator',
          value: 'winda osobowa obsługująca scenę główną, sale baletowe i galerię Beksińskiego',
          status: 'verified',
          source: {
            name: 'BIP NCK / Deklaracja Dostępności (KSDK)',
            url: 'https://nck.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-umk-glowny',
      name: 'Urząd Miasta Krakowa - Siedziba Główna',
      label: 'pl. Wszystkich Świętych 3-4, Kraków (Stare Miasto)',
      position: { lon: 19.9383, lat: 50.0592 },
      category: 'office',
      isSample: true,
      facts: [
        {
          id: 'place-umk-glowny-entrance',
          subject: { type: 'entrance', ref: 'node/umk-glowny-entrance', lat: 50.0592, lon: 19.9383 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście do sieni głównej z podjazdem, dzwonek asystencyjny przy drzwiach)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-umk-glowny-services',
          subject: { type: 'place', ref: 'node/umk-glowny-inside', lat: 50.0592, lon: 19.9383 },
          criterion: 'hearing_loop',
          value: 'pętla indukcyjna na Dzienniku Podawczym, tłumacz języka migowego PJM on-line',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-umk-glowny-lift',
          subject: { type: 'place', ref: 'node/umk-glowny-lift', lat: 50.0592, lon: 19.9383 },
          criterion: 'highway:elevator',
          value: 'winda osobowa w sieni z komunikatami głosowymi i oznaczeniami Braille',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-umk-powstania',
      name: 'UMK Wydział Spraw Administracyjnych',
      label: 'al. Powstania Warszawskiego 10, Kraków (Grzegórzki)',
      position: { lon: 19.9615, lat: 50.0595 },
      category: 'office',
      isSample: true,
      facts: [
        {
          id: 'place-umk-powstania-entrance',
          subject: { type: 'entrance', ref: 'node/umk-powstania-entrance', lat: 50.0595, lon: 19.9615 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście z poziomu chodnika bez progów, automatycznie otwierane drzwi)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-umk-powstania-counters',
          subject: { type: 'place', ref: 'node/umk-powstania-hall', lat: 50.0595, lon: 19.9615 },
          criterion: 'hearing_loop',
          value: 'stanowiska dowodów i meldunków z obniżonym blatem, pętla indukcyjna, system kolejkowy audio',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-umk-wielicka',
      name: 'UMK Wydział Architektury i Urbanistyki',
      label: 'ul. Wielicka 28a, Kraków (Podgórze)',
      position: { lon: 19.9644, lat: 50.0381 },
      category: 'office',
      isSample: true,
      facts: [
        {
          id: 'place-umk-wielicka-entrance',
          subject: { type: 'entrance', ref: 'node/umk-wielicka-entrance', lat: 50.0381, lon: 19.9644 },
          criterion: 'entrance:wheelchair',
          value: 'yes (szeroka rampa podjazdowa o nachyleniu 5%, drzwi przesuwne fotokomórka)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-umk-wielicka-elevators',
          subject: { type: 'place', ref: 'node/umk-wielicka-elevators', lat: 50.0381, lon: 19.9644 },
          criterion: 'highway:elevator',
          value: '2 przestronne windy obsługujące wszystkie piętra, toalety PRM na każdej kondygnacji',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-umk-zgody',
      name: 'UMK Punkt Obsługi Mieszkańców (Nowa Huta)',
      label: 'os. Zgody 2, Kraków (Nowa Huta)',
      position: { lon: 20.0382, lat: 50.0735 },
      category: 'office',
      isSample: true,
      facts: [
        {
          id: 'place-umk-zgody-entrance',
          subject: { type: 'entrance', ref: 'node/umk-zgody-entrance', lat: 50.0735, lon: 20.0382 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście płaskie z poziomu chodnika, szeroki wiatrołap)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-usc-grunwaldzka',
      name: 'Urząd Stanu Cywilnego w Krakowie',
      label: 'ul. Grunwaldzka 8, Kraków',
      position: { lon: 19.9658, lat: 50.0638 },
      category: 'office',
      isSample: true,
      facts: [
        {
          id: 'place-usc-entrance',
          subject: { type: 'entrance', ref: 'node/usc-entrance', lat: 50.0638, lon: 19.9658 },
          criterion: 'entrance:wheelchair',
          value: 'yes (zewnętrzna rampa z poręczami prowadząca do sieni głównej)',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-usc-lift',
          subject: { type: 'place', ref: 'node/usc-lift', lat: 50.0638, lon: 19.9658 },
          criterion: 'highway:elevator',
          value: 'winda osobowa dostępna na I piętro do sal ślubów i archiwum',
          status: 'verified',
          source: {
            name: 'BIP Miasta Krakowa / Deklaracja Dostępności UMK',
            url: 'https://bip.krakow.pl/?dok_id=123015',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-dworzec-glowny',
      name: 'Dworzec Główny PKP Kraków',
      label: 'pl. Jana Nowaka-Jeziorańskiego 3, Kraków',
      position: { lon: 19.9482, lat: 50.0664 },
      category: 'transit',
      isSample: true,
      facts: [
        {
          id: 'place-dworzec-pkp-entrance',
          subject: { type: 'entrance', ref: 'node/dworzec-pkp-entrance', lat: 50.0664, lon: 19.9482 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wielopoziomowy węzeł z windami i schodami ruchomymi zintegrowany z Galerią Krakowską)',
          status: 'verified',
          source: {
            name: 'Portal Pasażera PKP PLK / Deklaracja Dostępności',
            url: 'https://pkp.pl/dostepnosc-stacji',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-dworzec-pkp-elevators',
          subject: { type: 'place', ref: 'node/dworzec-pkp-elevators', lat: 50.0664, lon: 19.9482 },
          criterion: 'highway:elevator',
          value: 'windy na wszystkie perony 1-5 oraz do tunelu Magda i podziemnego tramwaju KST',
          status: 'verified',
          source: {
            name: 'Portal Pasażera PKP PLK / Deklaracja Dostępności',
            url: 'https://pkp.pl/dostepnosc-stacji',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-dworzec-pkp-assistance',
          subject: { type: 'place', ref: 'node/dworzec-pkp-assist', lat: 50.0664, lon: 19.9482 },
          criterion: 'tactile_paving',
          value: 'linie naprowadzające i pola uwagi na peronach, całodobowa usługa asysty PRM',
          status: 'verified',
          source: {
            name: 'Portal Pasażera PKP PLK / Deklaracja Dostępności',
            url: 'https://pkp.pl/dostepnosc-stacji',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-krakow-plaszow',
      name: 'Stacja Kolejowa Kraków Płaszów',
      label: 'pl. Braci Dudzińskich 1, Kraków (Podgórze)',
      position: { lon: 19.9772, lat: 50.0348 },
      category: 'transit',
      isSample: true,
      facts: [
        {
          id: 'place-plaszow-elevators',
          subject: { type: 'place', ref: 'node/plaszow-elevators', lat: 50.0348, lon: 19.9772 },
          criterion: 'highway:elevator',
          value: 'windy z tunelu podziemnego na perony 1, 2 i 3',
          status: 'verified',
          source: {
            name: 'PKP PLK / Deklaracja Dostępności',
            url: 'https://plk-sa.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-plaszow-ramp',
          subject: { type: 'entrance', ref: 'node/plaszow-ramp', lat: 50.0348, lon: 19.9772 },
          criterion: 'ramp',
          value: 'zadaszona rampa wejściowa od strony ul. Dworcowej',
          status: 'verified',
          source: {
            name: 'PKP PLK / Deklaracja Dostępności',
            url: 'https://plk-sa.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-mda-bosacka',
      name: 'MDA Dworzec Autobusowy Kraków',
      label: 'ul. Bosacka 18, Kraków',
      position: { lon: 19.9497, lat: 50.0683 },
      category: 'transit',
      isSample: true,
      facts: [
        {
          id: 'place-mda-entrance',
          subject: { type: 'entrance', ref: 'node/mda-entrance', lat: 50.0683, lon: 19.9497 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście płaskie od ul. Bosackiej i przez antresolę dworca PKP)',
          status: 'verified',
          source: {
            name: 'Małopolskie Dworce Autobusowe / Deklaracja Dostępności',
            url: 'https://mda.malopolska.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-mda-elevators',
          subject: { type: 'place', ref: 'node/mda-elevators', lat: 50.0683, lon: 19.9497 },
          criterion: 'highway:elevator',
          value: 'winda łącząca płytę dolną z górną i poczekalnią',
          status: 'verified',
          source: {
            name: 'Małopolskie Dworce Autobusowe / Deklaracja Dostępności',
            url: 'https://mda.malopolska.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-rondo-mogilskie',
      name: 'Węzeł Przesiadkowy Rondo Mogilskie',
      label: 'Rondo Mogilskie, Kraków (Grzegórzki)',
      position: { lon: 19.9602, lat: 50.0652 },
      category: 'transit',
      isSample: true,
      facts: [
        {
          id: 'place-mogilskie-elevators',
          subject: { type: 'place', ref: 'node/mogilskie-elevators', lat: 50.0652, lon: 19.9602 },
          criterion: 'highway:elevator',
          value: '4 windy łączące poziom dolny -1 (tramwaje) z poziomem górnym 0 (przystanki autobusowe)',
          status: 'verified',
          source: {
            name: 'Zarząd Transportu Publicznego w Krakowie (ZTP)',
            url: 'https://ztp.krakow.pl',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-mogilskie-ramps',
          subject: { type: 'segment', ref: 'way/mogilskie-ramps', lat: 50.0652, lon: 19.9602 },
          criterion: 'ramp',
          value: 'szerokie pochylnie zjazdowe o łagodnym kącie nachylenia ze wszystkich kierunków',
          status: 'verified',
          source: {
            name: 'Zarząd Dróg Miasta Krakowa (ZDMK)',
            url: 'https://zdmk.krakow.pl',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-narutowicz',
      name: 'Szpital Specjalistyczny im. G. Narutowicza',
      label: 'ul. Prądnicka 35, Kraków (Krowodrza)',
      position: { lon: 19.9372, lat: 50.0825 },
      category: 'health',
      isSample: true,
      facts: [
        {
          id: 'place-narutowicz-entrance',
          subject: { type: 'entrance', ref: 'node/narutowicz-entrance', lat: 50.0825, lon: 19.9372 },
          criterion: 'entrance:wheelchair',
          value: 'yes (Izba Przyjęć i SOR z podjazdem dla karetek i wózków inwalidzkich)',
          status: 'verified',
          source: {
            name: 'BIP Szpitala / Otwarte Dane Kraków',
            url: 'https://narutowicz.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-narutowicz-elevators',
          subject: { type: 'place', ref: 'node/narutowicz-elevators', lat: 50.0825, lon: 19.9372 },
          criterion: 'highway:elevator',
          value: 'windy łóżkowe i osobowe łączące wszystkie oddziały szpitalne',
          status: 'verified',
          source: {
            name: 'BIP Szpitala / Otwarte Dane Kraków',
            url: 'https://narutowicz.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-szpital-uniwersytecki',
      name: 'Szpital Uniwersytecki (Nowa Siedziba Prokocim)',
      label: 'ul. Jakubowskiego 2, Kraków (Prokocim)',
      position: { lon: 20.0076, lat: 50.0094 },
      category: 'health',
      isSample: true,
      facts: [
        {
          id: 'place-su-entrance',
          subject: { type: 'entrance', ref: 'node/su-entrance', lat: 50.0094, lon: 20.0076 },
          criterion: 'entrance:wheelchair',
          value: 'yes (nowoczesny kompleks 100% bez barier, wejścia w poziomie terenu, automatyczne rozsuwane drzwi)',
          status: 'verified',
          source: {
            name: 'BIP Szpitala Uniwersyteckiego / Deklaracja Dostępności',
            url: 'https://su.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-su-elevators',
          subject: { type: 'place', ref: 'node/su-elevators', lat: 50.0094, lon: 20.0076 },
          criterion: 'highway:elevator',
          value: 'kilkadziesiąt wind osobowych z syntezą mowy, alfabetem Braille i systemem priorytetów',
          status: 'verified',
          source: {
            name: 'BIP Szpitala Uniwersyteckiego / Deklaracja Dostępności',
            url: 'https://su.krakow.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-zeromski',
      name: 'Szpital Specjalistyczny im. S. Żeromskiego',
      label: 'os. Na Skarpie 66, Kraków (Nowa Huta)',
      position: { lon: 20.0452, lat: 50.0691 },
      category: 'health',
      isSample: true,
      facts: [
        {
          id: 'place-zeromski-entrance',
          subject: { type: 'entrance', ref: 'node/zeromski-entrance', lat: 50.0691, lon: 20.0452 },
          criterion: 'entrance:wheelchair',
          value: 'yes (pochylnie normatywne przy wejściu do pawilonu diagnostycznego i izby przyjęć)',
          status: 'verified',
          source: {
            name: 'BIP Szpitala Żeromskiego / Otwarte Dane Kraków',
            url: 'https://zeromski-szpital.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-collegium-novum',
      name: 'Uniwersytet Jagielloński - Collegium Novum',
      label: 'ul. Gołębia 24, Kraków (Stare Miasto)',
      position: { lon: 19.9328, lat: 50.0602 },
      category: 'education',
      isSample: true,
      facts: [
        {
          id: 'place-novum-entrance',
          subject: { type: 'entrance', ref: 'node/novum-entrance', lat: 50.0602, lon: 19.9328 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście bezbarierowe od strony dziedzińca z automatyczną platformą)',
          status: 'verified',
          source: {
            name: 'Dział Dostępności UJ / Deklaracja Dostępności UJ',
            url: 'https://uj.edu.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-novum-lift',
          subject: { type: 'place', ref: 'node/novum-lift', lat: 50.0602, lon: 19.9328 },
          criterion: 'highway:elevator',
          value: 'winda panoramiczna umożliwiająca dostęp do Auli Głównej i dziekanatów',
          status: 'verified',
          source: {
            name: 'Dział Dostępności UJ / Deklaracja Dostępności UJ',
            url: 'https://uj.edu.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-agh-a0',
      name: 'AGH Budynek Główny A-0',
      label: 'al. Mickiewicza 30, Kraków (Czarna Wieś)',
      position: { lon: 19.9192, lat: 50.0656 },
      category: 'education',
      isSample: true,
      facts: [
        {
          id: 'place-agh-entrance',
          subject: { type: 'entrance', ref: 'node/agh-entrance', lat: 50.0656, lon: 19.9192 },
          criterion: 'entrance:wheelchair',
          value: 'yes (rampa dostępowa z tyłu gmachu, drzwi automatyczne z przyciskiem)',
          status: 'verified',
          source: {
            name: 'Biuro ds. Osób z Niepełnosprawnościami AGH',
            url: 'https://bon.agh.edu.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-agh-lift',
          subject: { type: 'place', ref: 'node/agh-lift', lat: 50.0656, lon: 19.9192 },
          criterion: 'highway:elevator',
          value: 'winda osobowa z sygnalizacją dźwiękową i toaleta dostosowana na parterze',
          status: 'verified',
          source: {
            name: 'Biuro ds. Osób z Niepełnosprawnościami AGH',
            url: 'https://bon.agh.edu.pl/deklaracja-dostepnosci',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-pk-wil',
      name: 'Politechnika Krakowska - Wydział Inżynierii Lądowej',
      label: 'ul. Warszawska 24, Kraków (Kleparz)',
      position: { lon: 19.9458, lat: 50.0718 },
      category: 'education',
      isSample: true,
      facts: [
        {
          id: 'place-pk-entrance',
          subject: { type: 'entrance', ref: 'node/pk-entrance', lat: 50.0718, lon: 19.9458 },
          criterion: 'entrance:wheelchair',
          value: 'yes (pochylnia wejściowa od dziedzińca kampusu, platforma schodowa w holu)',
          status: 'verified',
          source: {
            name: 'Sekcja ds. Dostępności Politechniki Krakowskiej',
            url: 'https://pk.edu.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-tauron-arena',
      name: 'TAURON Arena Kraków',
      label: 'ul. Stanisława Lema 7, Kraków (Czyżyny)',
      position: { lon: 19.9845, lat: 50.0682 },
      category: 'sport',
      isSample: true,
      facts: [
        {
          id: 'place-tauron-entrance',
          subject: { type: 'entrance', ref: 'node/tauron-entrance', lat: 50.0682, lon: 19.9845 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wejście nr 1 dedykowane dla osób na wózkach, kasy z obniżonym blatem)',
          status: 'verified',
          source: {
            name: 'Zarząd Infrastruktury Sportowej w Krakowie (ZIS)',
            url: 'https://tauronarenakrakow.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-tauron-elevators',
          subject: { type: 'place', ref: 'node/tauron-elevators', lat: 50.0682, lon: 19.9845 },
          criterion: 'highway:elevator',
          value: '8 wind wielkogabarytowych obsługujących sektory A i C z miejscami dla wózków',
          status: 'verified',
          source: {
            name: 'Zarząd Infrastruktury Sportowej w Krakowie (ZIS)',
            url: 'https://tauronarenakrakow.pl/dostepnosc',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
    {
      id: 'sample-place-cracovia-sport',
      name: 'Centrum Sportu Niepełnosprawnych (Hala Cracovia)',
      label: 'al. Marszałka Ferdinanda Focha 40, Kraków (Błonia)',
      position: { lon: 19.9075, lat: 50.0578 },
      category: 'sport',
      isSample: true,
      facts: [
        {
          id: 'place-cracovia-entrance',
          subject: { type: 'entrance', ref: 'node/cracovia-entrance', lat: 50.0578, lon: 19.9075 },
          criterion: 'entrance:wheelchair',
          value: 'yes (wzorcowy obiekt referencyjny w 100% bez barier architektonicznych)',
          status: 'verified',
          source: {
            name: 'Zarząd Infrastruktury Sportowej w Krakowie (ZIS) / KSDK',
            url: 'https://zis.krakow.pl/obiekty/hala-100-lecia-cracovii',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
        {
          id: 'place-cracovia-features',
          subject: { type: 'place', ref: 'node/cracovia-features', lat: 50.0578, lon: 19.9075 },
          criterion: 'ramp',
          value: 'pochylnie o nachyleniu poniżej 4%, system pętli indukcyjnych na całej arenie',
          status: 'verified',
          source: {
            name: 'Zarząd Infrastruktury Sportowej w Krakowie (ZIS) / KSDK',
            url: 'https://zis.krakow.pl/obiekty/hala-100-lecia-cracovii',
            licence: 'Informacja Publiczna',
          },
          retrievedAt: '2026-10-03T11:00:00Z',
          lastConfirmedAt: '2026-04-15T10:00:00Z',
        },
      ],
    },
  ],
};
